apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-tc-app
  namespace: fiap-tc
  labels:
    app: fiap-tc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-tc
  template:
    metadata:
      labels:
        app: fiap-tc
    spec:
      containers:
      - name: fiap-tc-app
        image: DOCKER_REGISTRY_PLACEHOLDER/fiap-tech-challenge:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fiap-tc-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10