apiVersion: batch/v1
kind: Job
metadata:
  name: fiap-tc-db-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: db-migrations
        image: lucascq/fiap-tc:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for database to be ready at $DB_HOST_FOR_CHECK:$DB_PORT_FOR_CHECK..."
          timeout=120 # Pode aumentar se necessário para conexões externas
          # Use as variáveis de ambiente para o host e porta do banco
          while ! nc -z "$DB_HOST_FOR_CHECK" "$DB_PORT_FOR_CHECK"; do
            if [ $timeout -le 0 ]; then
              echo "Timed out waiting for database connection to $DB_HOST_FOR_CHECK:$DB_PORT_FOR_CHECK"
              exit 1
            fi
            timeout=$(($timeout - 1))
            echo "Waiting for database... $timeout seconds remaining"
            sleep 1
          done
          echo "Database is ready, running migrations and seed..."
          npx prisma migrate deploy
          npx prisma db seed
          echo "Database setup completed successfully"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fiap-tc-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fiap-tc-secrets
              key: DATABASE_URL
        - name: DB_HOST_FOR_CHECK 
          valueFrom:
            configMapKeyRef:
              name: fiap-tc-config
              key: POSTGRES_HOST
        - name: DB_PORT_FOR_CHECK 
          valueFrom:
            configMapKeyRef:
              name: fiap-tc-config
              key: POSTGRES_PORT
      restartPolicy: OnFailure