apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-tc-config
data:
  NODE_ENV: "production"
  AWS_ENDPOINT: "http://localstack:4566"
  POSTGRES_HOST: "tc-fiap-postgres.comilucshvgd.us-east-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fiap_tc_db"